### ISSUE TITLE
Zarf Name

### ISSUE THREAD

**Issue by jeff-mccoy** [bun-tea/bun-tea#23]
👋 current maintainer of [Zarf](https://zarf.dev) (https://github.com/defenseunicorns/zarf). I wanted to say hi and see how we can avoid name collisions. We're in the K8s / deployment env so it might not be an issue.  Thanks!

**Comment by one-aalam** [comment]
### _...and here I was thinking, I cracked a really unique name:-)_

Hi, @jeff-mccoy Thanks for reaching out. 

I thought there would be nothing by the name of "zarf"(arabic), and certainly, that's not the case here :-). Apologies, this name conflicts with your Golang tool. I definitely prefer to not call this just "Zarf" but "@zarfjs/zarf" as it's a JS Framework, and prevent any chances of conflict wherever possible.

**Comment by jeff-mccoy** [comment]
Wow, I have no idea why my notifications never popped up this reply!  That makes total sense, good luck with the project!
